### ISSUE TITLE
Is there a way to fallback to local login when LDAP fails?

### ISSUE THREAD

**Issue by cYbercOsmOnauT** [smartameer/nodebb-plugin-office-ldap#10]
We have the following situation. Some users from our company who are inside our AD and tons of external users who registers and are stored locally. It would help us alot if the plugin could try a local login if the LDAP fails.

**Comment by steel4me** [comment]
Yes, please, add this function. Maybe someone with dev skills can fork and implement it. Im only admin, can't code!

**Comment by smartameer** [comment]
@cYbercOsmOnauT, Let me add that option to check/uncheck if login fails from LDAP login locally. Thanks for your feedback.
