### ISSUE TITLE
Errors: undefined:undefined is an invalid LDAP url (protocol)

### ISSUE THREAD

**Issue by xinjingfen** [smartameer/nodebb-plugin-office-ldap#4]
NodeBB v1.4.3 or v1.3.0
node v4.3.0
Windows10

LDAP Settings:
![qq 20161121103617](https://cloud.githubusercontent.com/assets/8166881/23449397/4b13d922-fe91-11e6-9387-a50ad054363a.png)

when I login in:
![qq 20161121103617](https://cloud.githubusercontent.com/assets/8166881/23449493/c2d446a4-fe91-11e6-8602-c3373cf9bd11.png)

**Comment by wolf0x** [comment]
have you found the solution and fix it? I also meet the same error.

**Comment by msestellemarie** [comment]
Hi, I was having the same issue. Tracked it down to line 127 of the index.js [file](https://github.com/smartameer/nodebb-plugin-office-ldap/blob/master/index.js#L127). For some reason, it's not pulling the server url and port correctly when you enter them into the settings. I have a workaround to this problem. Enter your url info directly into the index.js file. For you, this would look like this.

````
override: function () {
            var options = {
                url: "ldap://10.45.52.130:389"
            };
````

**Comment by smartameer** [comment]
@xinjingfen & @wolf0x 

Try running `> nodebb dev` and check if settings are coming in console by adding `console.log(config);` in override method. Or there is always a solution as @msestellemarie said to change in code.

So far I haven't encountered such problem using the same nodebb version.

**Comment by wirepatch** [comment]
Like to join the club possible on account of a similar issue: I've also tweaked index.js (see attachment). Our (Open)LDAP bind DN representing a user `foo` looks like:
`uid=foo,ou=userlist,dc=hdm-stuttgart,dc=de`
So I modified subsequent lines of code accordingly. The LDAP bind part now works well this way. Unfortunately the login process subsequently fails:
```
uid=foo,ou=userlist,dc=hdm-stuttgart,dc=de|XYZ|ldap://learn.mi.hdm-stuttgart.de:389
19/5 21:59:47 [23161] - error:  TypeError: Cannot read property 'length' of undefined
    at Object.murmurhash3_32_gc (/opt/nodebb/node_modules/nodebb-plugin-office-ldap/index.js:73:28)
    at EventEmitter.<anonymous> (/opt/nodebb/node_modules/nodebb-plugin-office-ldap/index.js:164:50)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at sendResult (/opt/nodebb/node_modules/ldapjs/lib/client/client.js:1389:22)
    at messageCallback (/opt/nodebb/node_modules/ldapjs/lib/client/client.js:1411:14)
    at Parser.onMessage (/opt/nodebb/node_modules/ldapjs/lib/client/client.js:1089:14)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser.write (/opt/nodebb/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at Socket.onData (/opt/nodebb/node_modules/ldapjs/lib/client/client.js:1076:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```
Line numbers with respect to:
[index.zip](https://github.com/smartameer/nodebb-plugin-office-ldap/files/1015430/index.zip)

I do not quite understand the code in index.js but my feeling suspects a missing nodeBB profile of user `foo`. Registration had  been disabled prior to the login attempt and user `foo` does not yet exist on the NodeBB server. May this cause the problem?
Reading the documentation this point is unclear to me. We want our students to login without any prior nodeBB server arrangements. So on successful login registration shall happen at the same time.

**Comment by smartameer** [comment]
@wirepatch

`ldapsearch -H <Serverurl> -x -D <email> -w <password> -b <BaseDN> “(<Filter=value>)”
`

ex: ldapsearch -H ldap://myldapurl.ccom-x -D smartameer@icloud.com -w mypassword -b dc=icloud,dc=com “(sAMAccountName=smartameer)”


If this command will work in your Unix machine for fetching the result set of the user you are filtering for then the same logic has been maintained over there in the plugin.

When you are logging in with a user email and password, the file is just search or filters your name with sAmaccountName and with your email and password which has been entered. If there is an account available over ldap then it just creates a registration in nodebb with a ldap hash ID i.e. Murmur hash, or if there's an account already registered then it logs you in.

I am not sure if your basedn is correct to get result. With your ldapsearch just tweak what needs to be hashed like the plugin hashes the **displayName**.

**Comment by smartameer** [comment]
@xinjingfen , @wirepatch , @wolf0x I have released a new version `v1.0.4` with the bug fix. Give it a try. I have tested in my local with nodebb latest version.

**Comment by cotyp** [comment]
I have updated the plugin, and I am still getting the undefined, undefined error. To correct, I had to change the url on lines 133 and 148 in the index.js file . i.e: url: "ldap://myldapaddress.[port#]"

**Comment by qq5050595531** [comment]
I have the same problem. Is this fixed?
