### ISSUE TITLE
can describe more about the settings?

### ISSUE THREAD

**Issue by wolf0x** [smartameer/nodebb-plugin-office-ldap#5]
its too simple that make hard to understand how to setup the bypass login on NodeBB via the plugin. is it possible to describe more that how to setup the filter? just sAMAccountName? or  such as (&(objectCategory=Person)(sAMAccountName=*)) ???

**Comment by smartameer** [comment]
@wolf0x , the code now holds only the username based filter. i.e `sAMAccountName`

https://github.com/smartameer/nodebb-plugin-office-ldap/blob/master/index.js#L151

I will give fields based configuration and some placeholder which can accommodate the filter as you have asked `(&(objectCategory=Person)(sAMAccountName=*))`. 

It's simple based on just one unix command which has been integrated

`ldapsearch -H <Serverurl> -x -D <Email> -w <Password> -b <BaseDN> “(<Filter=value>)”`

Here `Email` and the Filter's value is same like **first.last@email.com** and **first.last** respectively.
