### ISSUE TITLE
Unable to activate plugin

### ISSUE THREAD

**Issue by wirepatch** [smartameer/nodebb-plugin-office-ldap#6]
I just did a fresh nodebb installation following https://nodebb.readthedocs.io/en/latest/installing/os/ubuntu.html. Then I did npm install nodebb-plugin-office-ldap in /opt/nodebb (expected npm confirmation)  followed by a chmod -R nodebb:nodebb /opt/nodebb. 

The ldap plugin shows up in Nodebb's plugin list but hitting the "Activate" button simply has no effect at all. What am I missing?

**Comment by smartameer** [comment]
@wirepatch Try activating using commandline

`> ./nodebb activate nodebb-plugin-office-ldap`

**Comment by wirepatch** [comment]
That did activate the plugin: I now see the option "Deactivate" rather than "activate" in the plugin list.
However with respect to https://github.com/smartameer/nodebb-plugin-office-ldap#user-content-desktop I still only see four options Composer .../ Persona ... / Markdown /Emoji but missing "LDAP settings". I restarted nodebb and did a fresh login

**Comment by smartameer** [comment]
@wirepatch 

Yes. I do know thats a problem. In UI it shows a toast to restart your nodebb server. so you might have to reload which will rebuild templates.

`>nodebb restart`

**Comment by wirepatch** [comment]
I completely re-installed NodeBB based on current v1.5.0 release. LDAP plugin installation and activation using NodeBB's GUI (rather than cli `./nodebb activate nodebb-plugin-office-ldap`) worked flawlessly by:

1.  Executing  `npm install nodebb-plugin-office-ldap` from `/opt/nodebb`
2.  Activating the plugin from inside NodeBB's GUI
3.  Executing `./nodebb restart` 

However hitting `PLUGING -> LDAP Settings` yields indefinite "sandclock" waiting returning no results. Related debug info is available at https://cloud.mi.hdm-stuttgart.de/owncloud/index.php/s/TETBzoM5arcVciS.
The file in question is located at `/opt/nodebb/node_modules/nodebb-plugin-office-ldap/templates/office_ldap.tpl` having 644 access and ownership `nodebb`.
I'm using an nginx proxy as being described at https://nodebb.readthedocs.io/en/latest/configuring/proxies/nginx.html. So far all other access worked transparently as expected.
Accessing the host using http and port 4567 yields an identical result.

**Comment by cYbercOsmOnauT** [comment]
I copied the file to the right position on my own to make it work.
