### ISSUE TITLE
Cannot open Plugins => LDAP settings page

### ISSUE THREAD

**Issue by andrewferdinandus** [smartameer/nodebb-plugin-office-ldap#8]
**Dashboard output**
Internal Error.
Oops! Looks like something went wrong!
/admin/plugins/office_ldap
Failed to lookup view "office_ldap" in views directory "/opt/nodebb/build/public/templates"

**log output**
4/10 11:05:40 [3473] - error: /assets/templates/office_ldap.jst
 Error: ENOENT: no such file or directory, open '/opt/nodebb/build/public/templates/office_ldap.tpl'

**Comment by AMRITPK** [comment]
Same issue here.. Any solution for this. looks like this is with newer versions of noddebb
